### PR TITLE
created vue components from html template

### PR DESCRIPTION
**Pull request by egentilucci**
Hi everybody, as decided on the issue #1 I created the following vue components:
- header-menu.vue
- main-spotlight.vue
- footer-form.vue

the components contain only the HTML part for now.

Let me know if they're ok.

Have a good evening!

### CODE REVIEW

**Comment by nmezzopera** [comment]
@Culdred thank you for working on this! The PR is too big, as we discussed in the issue we should have one PR for each component. Could you split this in 3 pieces?

**Comment by egentilucci** [comment]
@DonNicoJs you're right, it was clearly explained in the issue #1 my bad!
Thank you :) I'll split everything as instructed!

**Comment by egentilucci** [comment]
@DonNicoJs I have a question, as a best practice, should I delete this branch since the issue tied to it it's closed and will never be of use?

**Comment by nmezzopera** [comment]
> @DonNicoJs I have a question, as a best practice, should I delete this branch since the issue tied to it it's closed and will never be of use?

@Culdred Yep is good practice to keep them clean, if you don't do it, periodically the maintainer will do it tho

**Pull request closed without merging**
