### PR TITLE
added components to home, removed BasicComponent

### PR DESCRIPTION
**Pull request by egentilucci**
Hi :) @Arienlys @DonNicoJs in regards to **issue #9** I wired the components to `views/Home.vue`. @Arienlys thank you in advance for thaking the time to review it.

I would like to mention one thing, building the website locally I noticed that wiring the components in `Home.vue` the resulting page will show the vue-router links present in `App.vue` (links to `Home` and `Generic`) because is the root page and it contains such links. Apart from the styling which we didn't put yet, this is different from the original template of the website and I imagine we will deal with it later. Correct me if I'm wrong.

Lastly, I have a question, since in the original template `footer-form` and the `footer-contacts` are side by side (at least viewing the website from a resolutions bigger than a smartphone screen), we will deal with it when we style the page or is it something I could have done directly in the `<template>` section with this PR? If so, how to do it?

Have a nice day!

P.S.: I also removed the `BasicComponent` because I think it's not needed anymore.

### CODE REVIEW

**Comment by nmezzopera** [comment]
@Culdred 

> I would like to mention one thing, building the website locally I noticed that wiring the components in Home.vue the resulting page will show the vue-router links present in App.vue (links to Home and Generic) because is the root page and it contains such links. Apart from the styling which we didn't put yet, this is different from the original template of the website and I imagine we will deal with it later. Correct me if I'm wrong.

Correct we will deal with this later

> Lastly, I have a question, since in the original template footer-form and the footer-contacts are side by side (at least viewing the website from a resolutions bigger than a smartphone screen), we will deal with it when we style the page or is it something I could have done directly in the <template> section with this PR? If so, how to do it?

You are not forced to only use components! they can be mix and matched with any basic html element! In this case you may want to wrap them in a `<div>`

>P.S.: I also removed the BasicComponent because I think it's not needed anymore.

Well done!


@Arienlys please go trough the code and make your comments!

**Comment by Arienlys** [comment]
First: i'm terribly sorry to not have seen/reviewed this sooner.

Wired look good to me... because i know this way of writing it work (i think i already saw it) but i have a question tho:
i'm more used to see (and write) it like this for example:

`import HeaderMenu from "../components/header-menu";`
will give:
```
components: {
    header-menu: HeaderMenu,
  },
```
and
`<header-menu></header-menu>`

Is there one way better than the second or it's fine this way? (or maybe one is better for little project, the other is better for more important one?)

**Comment by egentilucci** [comment]
@Arienlys don't worry, it's not a problem at all!! :) thank you for taking the time to do it.

About your question:
- about the `components: { HeaderMenu }`, in Vue website at the **[component registration](https://vuejs.org/v2/guide/components-registration.html)** chapter (**Local registration** paragraph) they say that _if you’re using ES2015 modules, such as through Babel and Webpack_ you can use this shortened syntax, and so I used it.

- about the `<HeaderMenu />` I saw writing it with **self-closing tags** in some examples online (can't find the exact reference at the moment) and so did I, as it seems cleaner. I assumed is the same as as writing it with open and closing tags, but I don't know if doing it this way has some kind of cosequences.

Please @DonNicoJs correct me if I'm wrong or add if I forgot to mention something important, thank you :)

**Comment by nmezzopera** [comment]
@Culdred @Arienlys Now is me that needs to apologise on the speed! 

Both approaches:
```
components: {
    header-menu: HeaderMenu,
  },
```
and
`components: { HeaderMenu }` 

Are perfectly valid, but the second is much more common, the first approach is used mostly when one wants to change the name that he is going to use in the `template`

About self closing tags `<HeaderMenu />` this is also a matter of preferences, what is important is to be consistent

**Review by nmezzopera — APPROVED** [review]

**Comment by nmezzopera** [comment]
Hey everyone! This LGTM! 

Merging!

**Pull request merged**
